apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: app
spec:
  containers: 
    - name:  hello-world
      image: 270291036751.dkr.ecr.us-east-2.amazonaws.com/assignment-2:hello-world
      command:
      - cat
      tty: true