apiVersion: v1
kind: Pod
metadata:
  name: simple-web
  labels:
    app: web
spec:
  containers: 
    - name:   simple-web
      image:  yeasy/simple-web:latest
      ports:
        - containerPort: 80